config/urls.py
from django.contrib import admin
from django.urls import path, include
from news.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('news/', include('news.urls')),

]

news/urls.py
from django.urls import path
from . import views


app_name = 'news'

urlpatterns = [
    path('create/', views.news_create, name='create'),
    path('category/<str:category>/', views.news_by_category, name='category'),
    path('detail/<int:news_id>/', views.news_detail, name='detail'),
]

news/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone


class News(models.Model):
    title = models.CharField(max_length=200)
    short_content = models.TextField()
    long_content = models.TextField()
    category = models.CharField(max_length=100)
    author_name = models.CharField(max_length=100, default='Unknown')


    class Meta:
        verbose_name_plural = 'News'

    def get_detail_url(self):
        return reverse('news:detail', args=[self.pk])

news/views.py
from django.shortcuts import render, redirect, get_object_or_404
from.models import News

def home(request):
     articles = News.objects.all()
     ctx = {'articles': articles}
     return render(request, 'index.html', ctx)

def news_create(request):
    if request.method == 'POST':
          author_name = request.POST.get('author_name')
          title = request.POST.get('title')
          short_content = request.POST.get('short_content')
          long_content = request.POST.get('long_content')
          category = request.POST.get('category')
          if title and short_content and long_content and category:
             News.objects.create(
                 author_name=author_name,
                 title=title,
                 short_content=short_content,
                 long_content=long_content,
                 category=category,
               )
             return redirect('home')
    return render(request, 'news/add-news.html',)


def news_by_category(request, category):
    articles = News.objects.filter(category=category)
    ctx = {
          'articles': articles,
          'category': category,
    }
    return render(request, 'news/news-by-category.html', ctx)


def news_detail(request, news_id):
    article = get_object_or_404(News, pk=news_id)
    ctx = {'article': article}
    return render(request, 'news/detail.html', ctx)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {# HEADER #}
    {% include 'includes/header.html' %}

    {# NAVBAR #}
    {% include 'includes/nav.html' %}
    <div class="container">
        {# MAIN CONTENT #}
        {% block content %} {% endblock %}
    </div>
        {# FOOTER #}
        {% include 'includes/footer.html' %}
</body>
</html>

templates/includes/footer.html
<footer>
    <p>&copy; 2023 Yangiliklar Sayti. Barcha huquqlar himoyalangan.</p>
</footer>

templates/includes/header.html
<header>
  <h1>Yangiliklar Sayti</h1>
</header>

templates/includes/nav.html
<nav>
    <ul>
        <li><a href="{% url 'home' %}">Bosh Sahifa</a></li>
        <li><a href="{% url 'news:category' 'mahalliy' %}">Mahalliy</a></li>
        <li><a href="{% url 'news:category' 'jahon' %}">Jahon</a></li>
        <li><a href="{% url 'news:category' 'sport' %}">Sport</a></li>
        <li><a href="{% url 'news:category' 'texnologiya' %}">Texnologiya</a></li>
        <li><a href="{% url 'news:create' %}">Yangilik Qo'shish</a></li>
    </ul>
</nav>

templates/index.html
{% extends 'base.html' %}
{% block title %} {{ category|title }} Tafsilotlari {% endblock %}
{% block content %}
    <div class="container">
        {% for article in articles %}
        <div class="news-item">
                <h2>{{ article.title }}</h2>
                <p>{{ article.short_content }}</p>
                <a href="{{ article.get_detail_url }}" class="read-more">Batafsil</a>
        </div>
        {% empty %}
            <h2>Hech narsa topilmadi</h2>
        {% endfor %}
    </div>
{% endblock %}

templates/news/add-news.html
{% extends 'base.html' %}
{% block title %} Yangilik Qo'shish {% endblock %}
{% block content %}
<div class="container">
        <h2>Yangi Yangilik Qo'shish</h2>
    <form class="news-form" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="author_name">Muallif Ismi:</label>
                <input type="text" id="author_name" name="author_name"  required>
            </div>

            <div class="form-group">
                <label for="title">Sarlavha:</label>
                <input type="text" id="title" name="title" required>
            </div>
            <div class="form-group">
                <label for="category">Kategoriya:</label>
                <select id="category" name="category" required>
                    <option value="">Tanlang</option>
                    <option value="mahalliy">Mahalliy</option>
                    <option value="jahon">Jahon</option>
                    <option value="sport">Sport</option>
                    <option value="texnologiya">Texnologiya</option>
                </select>
            </div>
            <div class="form-group">
                <label for="short_content">Qisqa tavsif:</label>
                <textarea id="short_content" name="short_content" required></textarea>
            </div>
            <div class="form-group">
                <label for="long_content">To'liq matn:</label>
                <textarea id="long_content" name="long_content" required></textarea>
            </div>
            <button type="submit" class="submit-btn">Yangilik qo'shish</button>
    </form>
    </div>
{% endblock %}

templates/news/detail.html
{% extends 'base.html'%}
{% block title %} {{ category|title }} Tafsilotlar {% endblock %}
{% block content %}
    <div class="news-item">
         <a href="{% url 'home' %}" class="read-more">Back to Home</a>
    </div>
        <div class="container">
            <article class="news-detail">
                <h2>{{ category|title }} Sarlavhasi</h2>
                <p class="news-meta">Sana:{{ article.created_at|date:"Y~m~d" }} | Muallif:{{ article.author_name|default:'Unknown' }}</p>
                <div class="news-content">
                    <p>{{ article.long_content }}</p>
                </div>
            </article>
        </div>
{% endblock %}

templates/news/news-by-category.html
{% extends 'base.html' %}
{% block title %} {{ category|title }} Yangiliklari {% endblock %}
{% block content %}
    <div class="container">
        <h2 id="category-title">
            {% if category %}
                {{ category|title }} Yangiliklari
            {% else %}
                Barcha Yangiliklar
            {% endif %}
        </h2>
        <div id="news-list">
            {% if articles %}
                {% for article in articles %}
                    <div class="news-item">
                        <h3>{{ article.title }}</h3>
                        <p>{{ article.short_content }}</p>
                        <a href="{{ article.get_detail_url }}" class="read-more">Batafsil</a>
                    </div>
                {% endfor %}
            {% else %}
                <p>Hozircha yangiliklar mavjud emas.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}